### ISSUE TITLE
about batch_size

### ISSUE THREAD

**Issue by zhouhuiwang** [giovcandido/prototypical-networks-project#1]
Hey:
 when I run your code, training.py on miniimagenet, there is a cuda out of memory problem, so I try to decrease the batch_size,
but I can not find the batch_size, can you help me?
thank you

**Comment by giovcandido** [comment]
Hey there!

I had this same problem before upgrading the machine I used to run the training on mini-ImageNet. 

One way you could avoid "cuda out of memory" is decreasing the number of images the code has to deal with in each episode. 

In the config directory, there's the config.yaml. In this file you can change the few-shot setup the way you need.

Open the file and find the following section:

```yaml
# mini_imagenet parameters
mini_imagenet:
  train:
    num_way: 20
    num_shot: 5
    num_query: 15
    epoch_size: 100  
```

You can experiment with these values and see if the problem goes away.

Try decreasing the shot, the query or even the way.

If you need further explanation, let me know.

I'm glad to help you.
